export const data =
[
  {
   "number": 1,
   "no_katalog_data": "686072.2023.001",
   "kode_satker": 686072,
   "tahun": 2023,
   "no_urut": "001",
   "satker": "Biro Humas Setjen Kemhan",
   "nama_dataset": "Jumlah Produksi Konten \nPada Media Cetak Dan\nMedia Online",
   "objek_data": "Produksi konten pada media cetak dan media online",
   "variabel_pembentuk": "Nomor, Jenis Media, Bulan Jumlah per Bulan, Total per Tahun.",
   "format_dokumen_data": "Excel",
   "status": "Terbuka",
   "produsen_data": "Subbag Pembentukan\nBag Opini Biro Humas Setjen Kemhan",
   "jadwal_pemutakhiran": "Pertahun",
   "tagging_data_prioritas": "",
   "prioritas_nasional": "",
   "program_prioritas": "",
   "kesepakatan_berbagi_data": "",
   "link_api": "Akan disiapkan",
   "kesepakatan_pengumpulan_data": 0,
   "catatan" : "",
   "dasar_hukum": "Undang-Undang Nomor 14 Tahun 2008 tentang Keterbukaan Informasi Publik "
  },
  {
   "number": 2,
   "no_katalog_data": "686072.2023.002",
   "kode_satker": 686072,
   "tahun": 2023,
   "no_urut": "002",
   "satker": "Biro Humas Setjen Kemhan",
   "nama_dataset": "Jumlah Produksi Konten Podcast",
   "objek_data": "Produksi konten podcast",
   "variabel_pembentuk": "Nomor, Nama Giat, Bulan, Jumlah per Bulan, Total per Tahun.",
   "format_dokumen_data": "Excel",
   "status": "Terbuka",
   "produsen_data": "Subbag Pembentukan Bag Opini Biro Humas Setjen Kemhan",
   "jadwal_pemutakhiran": "Pertahun",
   "link_api": "Akan disiapkan",
   "kesepakatan_pengumpulan_data": 0,
   "dasar_hukum": "Undang-Undang Nomor 14 Tahun 2008 tentang Keterbukaan Informasi Publik "
  },
  {
   "number": 3,
   "no_katalog_data": "686072.2023.003",
   "kode_satker": 686072,
   "tahun": 2023,
   "no_urut": "003",
   "satker": "Biro Humas Setjen Kemhan",
   "nama_dataset": "Jumlah Produksi Konten pada Media Sosial Kemhan",
   "objek_data": "Produksi Konten Pada Media Sosial Kemhan",
   "variabel_pembentuk": "Nomor, Nama Sosial Media, Bulan, Jumlah per Bulan, Total per Tahun.",
   "format_dokumen_data": "Excel",
   "status": "Terbuka",
   "produsen_data": "Subbag Opini Media Internet Bag Opini Biro Humas Setjen Kemhan",
   "jadwal_pemutakhiran": "Pertahun",
   "link_api": "Akan disiapkan",
   "kesepakatan_pengumpulan_data": 0,
   "dasar_hukum": "Undang-Undang Nomor 14 Tahun 2008 tentang Keterbukaan Informasi Publik "
  },
  {
   "number": 4,
   "no_katalog_data": "686072.2023.004",
   "kode_satker": 686072,
   "tahun": 2023,
   "no_urut": "004",
   "satker": "Biro Humas Setjen Kemhan",
   "nama_dataset": "Jumlah Naskah Sambutan Pimpinan Lembaga Non-Pemerintah",
   "objek_data": "Naskah Sambutan Pimpinan Lembaga Non-Pemerintah",
   "variabel_pembentuk": "Nomor, Koordinasi, Bulan, Jumlah per Bulan, Total per Tahun.",
   "format_dokumen_data": "Excel",
   "status": "Terbuka",
   "produsen_data": "Subbag Hubungan Lembaga Non Pemerintah Bag Hubmitra Biro Humas Setjen Kemhan",
   "jadwal_pemutakhiran": "Pertahun",
   "link_api": "Akan disiapkan",
   "kesepakatan_pengumpulan_data": 0,
   "dasar_hukum": "Undang-Undang Nomor 14 Tahun 2008 tentang Keterbukaan Informasi Publik "
  },
  {
   "number": 5,
   "no_katalog_data": "686072.2023.005",
   "kode_satker": 686072,
   "tahun": 2023,
   "no_urut": "005",
   "satker": "Biro Humas Setjen Kemhan",
   "nama_dataset": "Jumlah Naskah Sambutan Pimpinan Lembaga Pemerintah",
   "objek_data": "Naskah Sambutan Pimpinan Lembaga  Pemerintah",
   "variabel_pembentuk": "Nomor, Koordinasi, Bulan, Jumlah per Bulan, Total per Tahun.",
   "format_dokumen_data": "Excel",
   "status": "Terbuka",
   "produsen_data": "Subbag Hubungan Lembaga   Pemerintah Bag Hubmitra Biro Humas Setjen Kemhan",
   "jadwal_pemutakhiran": "Pertahun",
   "link_api": "Akan disiapkan",
   "kesepakatan_pengumpulan_data": 0,
   "dasar_hukum": "Undang-Undang Nomor 14 Tahun 2008 tentang Keterbukaan Informasi Publik "
  },
  {
   "number": 6,
   "no_katalog_data": "686072.2023.006",
   "kode_satker": 686072,
   "tahun": 2023,
   "no_urut": "006",
   "satker": "Biro Humas Setjen Kemhan",
   "nama_dataset": "Jumlah Kordinasi\/Rapat\/FGD\/Seminar\/Kunjungan Antar Lembaga Pemerintah Secara Online dan Tatap Muka",
   "objek_data": "Kordinasi\/Rapat\/FGD\/Seminar\/Kunjungan Antar Lembaga Pemerintah Secara Online Dan Tatap Muka",
   "variabel_pembentuk": "Nomor, Koordinasi, Bulan, Jumlah per Bulan, Total per Tahun.",
   "format_dokumen_data": "Excel",
   "status": "Terbuka",
   "produsen_data": "Subbag Hubungan Lembaga Non Pemerintah Bag Hubmitra Biro Humas Setjen Kemhan",
   "jadwal_pemutakhiran": "Pertahun",
   "link_api": "Akan disiapkan",
   "kesepakatan_pengumpulan_data": 0,
   "dasar_hukum": "Undang-Undang Nomor 14 Tahun 2008 tentang Keterbukaan Informasi Publik "
  },
  {
   "number": 7,
   "no_katalog_data": "686072.2023.007",
   "kode_satker": 686072,
   "tahun": 2023,
   "no_urut": "007",
   "satker": "Biro Humas Setjen Kemhan",
   "nama_dataset": "Status Pengaduan dan Permohonan Informasi",
   "objek_data": "Pengaduan dan permohonan informasi",
   "variabel_pembentuk": "Nomor, Proses, Bulan, Jumlah per Bulan, Total per Tahun.",
   "format_dokumen_data": "Excel",
   "status": "Terbuka",
   "produsen_data": "Subbag Yaninfopublik Bag Infopubliktaka Biro Humas Setjen Kemhan",
   "jadwal_pemutakhiran": "Pertahun",
   "link_api": "Akan disiapkan",
   "kesepakatan_pengumpulan_data": 0,
   "dasar_hukum": "Undang-Undang Nomor 14 Tahun 2008 tentang Keterbukaan Informasi Publik "
  },
  {
   "number": 8,
   "no_katalog_data": "686072.2023.008",
   "kode_satker": 686072,
   "tahun": 2023,
   "no_urut": "008",
   "satker": "Biro Humas Setjen Kemhan",
   "nama_dataset": "Status Pengaduan dan Permohonan Informasi",
   "objek_data": "Pengaduan dan permohonan informasi",
   "variabel_pembentuk": "Nomor, Saluran Pengaduan, Jumlah per Bulan, Total per Tahun.",
   "format_dokumen_data": "Excel",
   "status": "Terbuka",
   "produsen_data": "Subbag Yaninfopublik Bag Infopubliktaka Biro Humas Setjen Kemhan",
   "jadwal_pemutakhiran": "Pertahun",
   "link_api": "Akan disiapkan",
   "kesepakatan_pengumpulan_data": 0,
   "dasar_hukum": "Undang-Undang Nomor 14 Tahun 2008 tentang Keterbukaan Informasi Publik "
  },
  {
   "number": 9,
   "no_katalog_data": "683007.2023.001",
   "kode_satker": 683007,
   "tahun": 2023,
   "no_urut": "001",
   "satker": "Biro Turdang Setjen Kemhan",
   "nama_dataset": "Jaringan Data Informasi Hukum (JDIH)",
   "objek_data": "Himpunan Peraturan Perundang-undangan",
   "variabel_pembentuk": "Undang-undang, Peraturan Presiden, Peraturan Menteri Pertahanan, Peraturan Eselon I di Lingkungan Kemhan",
   "format_dokumen_data": "Excel",
   "status": "Terbuka",
   "produsen_data": "Bag Dokinfokum Biro Turdang Setjen Kemhan",
   "jadwal_pemutakhiran": "Real Time",
   "link_api": "Akan disiapkan",
   "kesepakatan_pengumpulan_data": 0,
   "dasar_hukum": "- Peraturan Presiden Nomor 33 Tahun 2012 tentang Jaringan Dokumentasi dan Informasi Hukum Nasional\n- Permenhan Nomor 36 Tahun 2018 tentang Jaringan Dokumentasi dan Informasi Hukum Kemhan\n- Permenhan Nomor 4 tahun 2023 tentang Pengelolaan Dokumentasi dan Informasi Hukum di Lingkungan Kemhan"
  },
  {
   "number": 10,
   "no_katalog_data": "683813.2023.001",
   "kode_satker": 683813,
   "tahun": 2023,
   "no_urut": "001",
   "satker": "lnspektorat Jenderal  Kemhan",
   "nama_dataset": "Data Pengawasan Intern (SIMWAS)",
   "objek_data": "Data Pengawasan Intern",
   "variabel_pembentuk": "Pemberitahuan  dan Permintaan   Data, Program   Kegiatan, Taklimat Awal, KKA Taklimat Akhir, Berita Acara, Lampiran PHP, LHP, Lampiran LHP, lntisari, Surat PPWP dan Lampiran PPWP.",
   "format_dokumen_data": "Excel",
   "status": "Rahasia",
   "produsen_data": "lnspektorat Jenderal  Kemhan",
   "jadwal_pemutakhiran": "Real Time",
   "kesepakatan_pengumpulan_data": 0,
   "dasar_hukum": "Permenhan  Nomor 19 Tahun 2020.\nTanggal 18 Oktober 2020 tentang Pengawasan Intern di Lingkungan Kemhan dan TNI."
  },
  {
   "number": 11,
   "no_katalog_data": "683813.2023.002",
   "kode_satker": 683813,
   "tahun": 2023,
   "no_urut": "002",
   "satker": "lnspektorat Jenderal  Kemhan",
   "nama_dataset": "LHKPN",
   "objek_data": "Data Harta Kekayaan Penyelenggara Negara Eselon I, II, Ill (yang mengelola anggaran), Pejabat Pembuat Auditor Madya dan Pengadaan Barang dan Jasa di lingkungan Kemhan",
   "variabel_pembentuk": "- KTP\n- Rekening Tabungan\n- Formulir Registrasi\n- Sertifikat\n- Bukti Lapor",
   "format_dokumen_data": "Excel",
   "status": "Rahasia",
   "produsen_data": "lnspektorat Jenderal  Kemhan",
   "jadwal_pemutakhiran": "Per Tahun",
   "kesepakatan_pengumpulan_data": 0,
   "dasar_hukum": "- Permenhan RI Nomor 29 Tahun 2019 tentang Laporan Harta Kekayaan Penyelenggara Negara (LHKPN) di lingkungan Kemhan.\n- Surat  Edaran lrjen Kemhan Nomor: 04\/XII\/2022 tentang Laporan Harta Kekayaan Penyelenggara Negara (LHKPN) Kementerian Pertahanan Tahun 2022."
  },
  {
   "number": 12,
   "no_katalog_data": "683813.2023.003",
   "kode_satker": 683813,
   "tahun": 2023,
   "no_urut": "003",
   "satker": "lnspektorat Jenderal  Kemhan",
   "nama_dataset": "LHKASN",
   "objek_data": "Data Harta Kekayaan seluruh\nAparatur Sipil Negara di lingkungan Kemhan",
   "variabel_pembentuk": "- KTP\n- Rekening Tabungan\n- Formulir Registrasi\n- Sertifikat\n- Bukti Lapor",
   "format_dokumen_data": "Excel",
   "status": "Rahasia",
   "produsen_data": "lnspektorat Jenderal  Kemhan",
   "jadwal_pemutakhiran": "Per Tahun",
   "kesepakatan_pengumpulan_data": 0,
   "dasar_hukum": "- Permenhan RI Nomor 54 Tahun 2016 tentang Laporan Harta Kekayaan Pegawai Aparatur Sipil Negara.\n- Surat  Edaran lrjen Kemhan Nomor: SE\/03\/XII\/2022 tentang Laporan Harta Kekayaan Aparatur Sipil Negara (LHKASN) Kemhan Tahun 2022."
  },
  {
   "number": 13,
   "no_katalog_data": "683813.2023.004",
   "kode_satker": 683813,
   "tahun": 2023,
   "no_urut": "004",
   "satker": "lnspektorat Jenderal  Kemhan",
   "nama_dataset": "SP4N LAPOR!",
   "objek_data": "Pengaduan Umum Eksternal dan Internal di lingkungan Kemhan dan TNI",
   "variabel_pembentuk": "Pelapor Pengaduan Tindak Lanjut Pengaduan",
   "format_dokumen_data": "Excel",
   "status": "Rahasia",
   "produsen_data": "lnspektorat Jenderal  Kemhan",
   "jadwal_pemutakhiran": "Real Time",
   "kesepakatan_pengumpulan_data": 0,
   "dasar_hukum": "- Peraturan Menteri PAN dan RB Nomor 62 Tahun 2018 tentang Pedoman Sistem Pengaduan Pelayanan Publik Nasional.\n- Keputusan Menteri PAN dan RB Nomor 680 Tahun 2020 tentang Aplikasi Umum Bidang Pengelolaan Pengaduan Pelayanan Publik.\n- Peraturan lrjen Kemhan Nomor 07 Tahun 2021 tanggal 13 April 2021 tentang Petunjuk Pelaksanaan Pengelolaan Pengaduan Publik di lingkungan Kemhan"
  },
  {
   "number": 14,
   "no_katalog_data": "683855.2023.001",
   "kode_satker": 683855,
   "tahun": 2023,
   "no_urut": "001",
   "satker": "Ditjen Kuathan Kemhan",
   "nama_dataset": "Rekapitulasi Kekuatan Prajurit TNI",
   "objek_data": "•\tRopeg Setjen Kemhan\n•\tMabes TNI\n•\tTNI AD\n•\tTNI AL\n•\tTNI AU",
   "variabel_pembentuk": "•\tPangkat\n•\tDalam Struktur (5 U.O.)\n•\tLuar Struktur\n•\tJumlah",
   "format_dokumen_data": "Excel",
   "status": "Terbatas",
   "produsen_data": "Subdit Rendiagasiskar Dit SDM Ditjen Kuathan Kemhan",
   "jadwal_pemutakhiran": "Triwulanan, Semesteran, Tahunan",
   "kesepakatan_pengumpulan_data": 0,
   "dasar_hukum": "Permenhan Nomor 2 Tahun 2013 tentang Sistem Pelaporan Kekuatan Personel Kementerian Pertahanan dan Tentara Nasional Indonesia"
  },
  {
   "number": 15,
   "no_katalog_data": "683855.2023.002",
   "kode_satker": 683855,
   "tahun": 2023,
   "no_urut": "002",
   "satker": "Ditjen Kuathan Kemhan",
   "nama_dataset": "Alokasi Penyediaan Prajurit TNI",
   "objek_data": "Data Penyediaan Prajurit TNI",
   "variabel_pembentuk": "•\tGolongan Pangkat\n•\tSuku Prajurit\n•\tMatra\n•\tJumlah",
   "format_dokumen_data": "Excel",
   "status": "Terbatas",
   "produsen_data": "Subdit Rendiagasiskar Dit SDM Ditjen Kuathan Kemhan",
   "jadwal_pemutakhiran": "Tahunan atau bila ada perubahan alokasi",
   "kesepakatan_pengumpulan_data": 0,
   "dasar_hukum": "•\tPP Nomor 39 Tahun 2010 tentang Administrasi Prajurit Tentara Nasional Indonesia\n•\tPermenhan Nomor 27 Tahun 2012 tentang Administrasi Penyediaan Prajurit Sukarela Tentara Nasional Indonesia"
  },
  {
   "number": 16,
   "no_katalog_data": "683855.2023.003",
   "kode_satker": 683855,
   "tahun": 2023,
   "no_urut": "003",
   "satker": "Ditjen Kuathan Kemhan",
   "nama_dataset": "Rekapitulasi Pemisahan Prajurit TNI",
   "objek_data": "•\tMabes TNI\n•\tTNI AD\n•\tTNI AL\n•\tTNI AU",
   "variabel_pembentuk": "•\tMatra\n•\tPDH (Alami, APS, MD)\n•\tPTDH\n•\tJumlah",
   "format_dokumen_data": "Excel",
   "status": "Terbatas",
   "produsen_data": "Subdit Sahlur Dit SDM Ditjen Kuathan Kemhan",
   "jadwal_pemutakhiran": "Triwulanan, Semesteran, Tahunan",
   "kesepakatan_pengumpulan_data": 0,
   "dasar_hukum": "Permenhan Nomor 4 Tahun 2015 tentang Sistem Pelaporan Pemisahan Prajurit Tentara Nasional Indonesia"
  },
  {
   "number": 17,
   "no_katalog_data": "683855.2023.004",
   "kode_satker": 683855,
   "tahun": 2023,
   "no_urut": "004",
   "satker": "Ditjen Kuathan Kemhan",
   "nama_dataset": "Rekapitulasi Prajurit TNI dan PNS yang Sedang Mengikuti Pendidikan Program S2\/S3 di Perguruan Tinggi Negeri",
   "objek_data": "Data Sertifikasi Kelaikan.",
   "variabel_pembentuk": "•\tNama, Pangkat, Jabatan\n•\tProgram, Jurusan\/Studi, PTN",
   "format_dokumen_data": "Excel",
   "status": "Terbatas",
   "produsen_data": "Subdit Bangdik Dit SDM Ditjen Kuathan Kemhan",
   "jadwal_pemutakhiran": "Tahunan atau bila ada perubahan",
   "kesepakatan_pengumpulan_data": 0,
   "dasar_hukum": "Permenhan Nomor 1 Tahun 2019 tentang Penyelenggaraan Tugas Belajar di Perguruan Tinggi bagi Prajurit Tentara Nasional Indonesia dan Pegawai Negeri Sipil Kementerian Pertahanan sebagaimana telah diubah dengan Permenhan Nomor 8 Tahun 2023"
  },
  {
   "number": 18,
   "no_katalog_data": "683855.2023.005",
   "kode_satker": 683855,
   "tahun": 2023,
   "no_urut": "005",
   "satker": "Ditjen Kuathan Kemhan",
   "nama_dataset": "Rekapitulasi Prajurit TNI dan PNS yang Sedang Mengikuti Pendidikan Keahlian Kesehatan",
   "objek_data": "\nData Rekap Prajurit TNI dan PNS",
   "variabel_pembentuk": "•\tNama, Pangkat, Jabatan\n•\tProgram, Jurusan\/Studi, PTN",
   "format_dokumen_data": "Excel",
   "status": "Terbatas",
   "produsen_data": "Subdit Nakes Ditkes Ditjen Kuathan Kemhan",
   "jadwal_pemutakhiran": "Tahunan atau bila ada perubahan",
   "kesepakatan_pengumpulan_data": 0,
   "dasar_hukum": "Permenhan Nomor 1 Tahun 2019 tentang Penyelenggaraan Tugas Belajar di Perguruan Tinggi bagi Prajurit Tentara Nasional Indonesia dan Pegawai Negeri Sipil Kementerian Pertahanan sebagaimana telah diubah dengan Permenhan Nomor 8 Tahun 2023"
  },
  {
   "number": 19,
   "no_katalog_data": "683855.2023.006",
   "kode_satker": 683855,
   "tahun": 2023,
   "no_urut": "006",
   "satker": "Ditjen Kuathan Kemhan",
   "nama_dataset": "Rekapitulasi Prajurit TNI dan PNS yang Sedang Mengikuti Pendidikan Keahlian Kesehatan dengan Pembiayaan dari Kemenkes",
   "objek_data": "Data Rekap Prajurit TNI dan PNS",
   "variabel_pembentuk": "•\tNama, Pangkat, Jabatan\n•\tProgram, Jurusan\/Studi, PTN",
   "format_dokumen_data": "Excel",
   "status": "Terbatas",
   "produsen_data": "Subdit Nakes Ditkes Ditjen Kuathan Kemhan",
   "jadwal_pemutakhiran": "Tahunan atau bila ada perubahan",
   "kesepakatan_pengumpulan_data": 0,
   "dasar_hukum": "Permenhan Nomor 1 Tahun 2019 tentang Penyelenggaraan Tugas Belajar di Perguruan Tinggi bagi Prajurit Tentara Nasional Indonesia dan Pegawai Negeri Sipil Kementerian Pertahanan sebagaimana telah diubah dengan Permenhan Nomor 8 Tahun 2023"
  },
  {
   "number": 20,
   "no_katalog_data": "683855.2023.007",
   "kode_satker": 683855,
   "tahun": 2023,
   "no_urut": "007",
   "satker": "Ditjen Kuathan Kemhan",
   "nama_dataset": "Rekapitulasi Taruna Akademi TNI yang Sedang Mengikuti Pendidikan Akademi Militer Luar Negeri",
   "objek_data": "Data Rekap Taruna Akademi TNI",
   "variabel_pembentuk": "•\tNama, No AK, Akademi\n•\tAkmil Luar Negeri",
   "format_dokumen_data": "Excel",
   "status": "Terbatas",
   "produsen_data": "Subdit Bangdik Dit SDM Ditjen Kuathan Kemhan",
   "jadwal_pemutakhiran": "Tahunan atau bila ada perubahan",
   "kesepakatan_pengumpulan_data": 0,
   "dasar_hukum": "Permenhan Nomor 24 Tahun 2016 tentang Beasiswa kepada Taruna\/Taruni Akademi Tentara Nasional Indonesia untuk Mengikuti Pendidikan Akademi Militer di Luar Negeri"
  },
  {
   "number": 21,
   "no_katalog_data": "683855.2023.008",
   "kode_satker": 683855,
   "tahun": 2023,
   "no_urut": "008",
   "satker": "Ditjen Kuathan Kemhan",
   "nama_dataset": "Rekapitulasi Data Usul Tanda Jasa dan Tanda Kehormatan",
   "objek_data": "•\tMabes TNI\n•\tTNI AD\n•\tTNI AL\n•\tTNI AU",
   "variabel_pembentuk": "•\tNama\n•\tPangkat\n•\tJabatan\n•\tJenis Tanda Jasa dan Tanda Kehormatan",
   "format_dokumen_data": "Excel",
   "status": "Terbatas",
   "produsen_data": "Subdit Watpers Dit SDM Ditjen Kuathan Kemhan",
   "jadwal_pemutakhiran": "Semester dan Tahunan",
   "kesepakatan_pengumpulan_data": 0,
   "dasar_hukum": "•\tUU 20 Tahun 2009 tentang Gelar, Tanda Jasa dan Tanda Kehormatan.\n•\tPP Nomor 35 tentang Pelaksanaan Undang-Undang 20 Tahun 2009 tentang Gelar, Tanda Jasa dan Tanda Kehormatan.\n•\tPermenhan Nomor 7Tahun 2017 tentang Pemberian Gelar, Tanda Jasa dan Tanda Kehormatan Bagi Prajurit TNI, WNI Bukan Prajurit TNI dan WNA."
  },
  {
   "number": 22,
   "no_katalog_data": "683855.2023.009",
   "kode_satker": 683855,
   "tahun": 2023,
   "no_urut": "009",
   "satker": "Ditjen Kuathan Kemhan",
   "nama_dataset": "Rekapitulasi Data Usul Penghargaan Dharma Pertahanan",
   "objek_data": "•\tPrajurit TNI\n•\tAnggota Polri\n•\tASN\n•\tWNI \n•\tWNA",
   "variabel_pembentuk": "•\tJenis Alutsista\n•\tJumlah\n•\tKondisi (B, RR, RB)",
   "format_dokumen_data": "Excel",
   "status": "Terbatas",
   "produsen_data": "Subdit Watpers Dit SDM Ditjen Kuathan Kemhan",
   "jadwal_pemutakhiran": "Semester dan Tahunan",
   "kesepakatan_pengumpulan_data": 0,
   "dasar_hukum": "•\tPermenhan Nomor 30 Tahun 2018 tentang Penghargaan Dharma Pertahanan.\n•\tPermenhan Nomor 2 Tahun 2023 tentang Perubahan atas Permenhan Nomor 30 Tahun 2018 tentang Penghargaan Dharma Pertahanan."
  },
  {
   "number": 23,
   "no_katalog_data": "683855.2023.010",
   "kode_satker": 683855,
   "tahun": 2023,
   "no_urut": "010",
   "satker": "Ditjen Kuathan Kemhan",
   "nama_dataset": "Rekapitulasi Data Kekuatan Alutsista Mabes TNI",
   "objek_data": "Data Kekuatan Alutsista Mabes TNI",
   "variabel_pembentuk": "•\tJenis Alutsista\n•\tJumlah\n•\tKondisi (B, RR, RB)",
   "format_dokumen_data": "Excel",
   "status": "Rahasia",
   "produsen_data": "Subdit Takol Ditmat Ditjen Kuathan Kemhan",
   "jadwal_pemutakhiran": "Triwulanan, Semesteran, Tahunan",
   "kesepakatan_pengumpulan_data": 0
  },
  {
   "number": 24,
   "no_katalog_data": "683855.2023.011",
   "kode_satker": 683855,
   "tahun": 2023,
   "no_urut": "011",
   "satker": "Ditjen Kuathan Kemhan",
   "nama_dataset": "Rekapitulasi Data Kekuatan Alutsista TNI AD",
   "objek_data": "Data Kekuatan Alutsista Mabes TNI AD",
   "variabel_pembentuk": "•\tJenis Alutsista\n•\tJumlah\n•\tKondisi (B, RR, RB)",
   "format_dokumen_data": "Excel",
   "status": "Rahasia",
   "produsen_data": "Subdit Takol Ditmat Ditjen Kuathan Kemhan",
   "jadwal_pemutakhiran": "Triwulanan, Semesteran, Tahunan",
   "kesepakatan_pengumpulan_data": 0
  },
  {
   "number": 25,
   "no_katalog_data": "683855.2023.012",
   "kode_satker": 683855,
   "tahun": 2023,
   "no_urut": "012",
   "satker": "Ditjen Kuathan Kemhan",
   "nama_dataset": "Rekapitulasi Data Kekuatan Alutsista TNI AL",
   "objek_data": "Data Kekuatan Alutsista Mabes TNI AL",
   "variabel_pembentuk": "•\tJenis Alutsista\n•\tJumlah\n•\tKondisi (B, RR, RB)",
   "format_dokumen_data": "Excel",
   "status": "Rahasia",
   "produsen_data": "Subdit Takol Ditmat Ditjen Kuathan Kemhan",
   "jadwal_pemutakhiran": "Triwulanan, Semesteran, Tahunan",
   "kesepakatan_pengumpulan_data": 0
  },
  {
   "number": 26,
   "no_katalog_data": "683855.2023.013",
   "kode_satker": 683855,
   "tahun": 2023,
   "no_urut": "013",
   "satker": "Ditjen Kuathan Kemhan",
   "nama_dataset": "Rekapitulasi Data Kekuatan Alutsista TNI AU",
   "objek_data": "Data Kekuatan Alutsista Mabes TNI AU",
   "variabel_pembentuk": "•\tJenis Alutsista\n•\tJumlah\n•\tKondisi (B, RR, RB)",
   "format_dokumen_data": "Excel",
   "status": "Rahasia",
   "produsen_data": "Subdit Takol Ditmat Ditjen Kuathan Kemhan",
   "jadwal_pemutakhiran": "Triwulanan, Semesteran, Tahunan",
   "kesepakatan_pengumpulan_data": 0
  },
  {
   "number": 27,
   "no_katalog_data": "683855.2023.014",
   "kode_satker": 683855,
   "tahun": 2023,
   "no_urut": "014",
   "satker": "Ditjen Kuathan Kemhan",
   "nama_dataset": "Rekapitulasi Pencapaian MEF (Minimum Essential Force)",
   "objek_data": "•\tMabes TNI\n•\tTNI AD\n•\tTNI AL\n•\tTNI AU",
   "variabel_pembentuk": "•\tMatra, Jenis Alutsista\n•\tJumlah sebelum MEF\n•\tJumlah\/Capaian MEF I\n•\tJumlah\/Capaian MEF II\n•\tPermenhan 39\/2015\n•\tProyeksi\/Capaian MEF III",
   "format_dokumen_data": "Excel",
   "status": "Rahasia",
   "produsen_data": "Subdit Renbutmat Ditmat Ditjen Kuathan Kemhan",
   "jadwal_pemutakhiran": "Triwulanan, Semesteran, Tahunan",
   "kesepakatan_pengumpulan_data": 0
  },
  {
   "number": 28,
   "no_katalog_data": "683855.2023.015",
   "kode_satker": 683855,
   "tahun": 2023,
   "no_urut": "015",
   "satker": "Ditjen Kuathan Kemhan",
   "nama_dataset": "Rekapitulasi Pencapaian Kekuatan Alpalhankam TNI dengan Penambahan Pemenuhannya",
   "objek_data": "•\tMabes TNI\n•\tTNI AD\n•\tTNI AL\n•\tTNI AU",
   "variabel_pembentuk": "•\tUpdate, KEP\/427\/M\/IV\/ 2022, Jumlah\n•\tEssential Force 5 Trouble Spot\n•\tSelisih\/Persentase",
   "format_dokumen_data": "Excel",
   "status": "Rahasia",
   "produsen_data": "Subdit Renbutmat Ditmat Ditjen Kuathan Kemhan",
   "jadwal_pemutakhiran": "Triwulanan, Semesteran, Tahunan",
   "kesepakatan_pengumpulan_data": 0
  },
  {
   "number": 29,
   "no_katalog_data": "683855.2023.016",
   "kode_satker": 683855,
   "tahun": 2023,
   "no_urut": "016",
   "satker": "Ditjen Kuathan Kemhan",
   "nama_dataset": "Rekapitulasi Penerimaan Hibah Materiil dari Luar Negeri yang Telah Selesai",
   "objek_data": "•\tMabes TNI\n•\tTNI AD\n•\tTNI AL\n•\tTNI AU",
   "variabel_pembentuk": "•\tNama Materiil\n•\tJumlah\n•\tPemberi Hibah\n•\tPenerima Hibah\n•\tNomor & Tanggal NPH",
   "format_dokumen_data": "Excel",
   "status": "Terbatas",
   "produsen_data": "Subdit Takol Ditmat Ditjen Kuathan Kemhan",
   "jadwal_pemutakhiran": "Triwulanan, Semesteran, Tahunan",
   "kesepakatan_pengumpulan_data": 0
  },
  {
   "number": 30,
   "no_katalog_data": "683855.2023.017",
   "kode_satker": 683855,
   "tahun": 2023,
   "no_urut": "017",
   "satker": "Ditjen Kuathan Kemhan",
   "nama_dataset": "Rekapitulasi Penerimaan Hibah Materiil dari Luar Negeri yang Masih Proses",
   "objek_data": "•\tMabes TNI\n•\tTNI AD\n•\tTNI AL\n•\tTNI AU",
   "variabel_pembentuk": "•\tNama Materiil\n•\tJumlah\n•\tPemberi Hibah\n•\tPenerima Hibah",
   "format_dokumen_data": "Excel",
   "status": "Terbatas",
   "produsen_data": "Subdit Takol Ditmat Ditjen Kuathan Kemhan",
   "jadwal_pemutakhiran": "Triwulanan, Semesteran, Tahunan",
   "kesepakatan_pengumpulan_data": 0
  },
  {
   "number": 31,
   "no_katalog_data": "683855.2023.018",
   "kode_satker": 683855,
   "tahun": 2023,
   "no_urut": "018",
   "satker": "Ditjen Kuathan Kemhan",
   "nama_dataset": "Rekapitulasi Pemberian Hibah Materiil Dalam Negeri",
   "objek_data": "•\tMabes TNI\n•\tTNI AD\n•\tTNI AL\n•\tTNI AU",
   "variabel_pembentuk": "•\tNama Materiil\n•\tJumlah\n•\tPemberi Hibah\n•\tPenerima Hibah",
   "format_dokumen_data": "Excel",
   "status": "Terbatas",
   "produsen_data": "Subdit Takol Ditmat Ditjen Kuathan Kemhan",
   "jadwal_pemutakhiran": "Triwulanan, Semesteran, Tahunan",
   "kesepakatan_pengumpulan_data": 0
  },
  {
   "number": 32,
   "no_katalog_data": "683855.2023.019",
   "kode_satker": 683855,
   "tahun": 2023,
   "no_urut": "019",
   "satker": "Ditjen Kuathan Kemhan",
   "nama_dataset": "Rekapitulasi Pemberian Hibah Materiil ke Luar Negeri",
   "objek_data": "•\tMabes TNI\n•\tTNI AD\n•\tTNI AL\n•\tTNI AU",
   "variabel_pembentuk": "•\tNama Materiil\n•\tJumlah\n•\tPemberi Hibah\n•\tPenerima Hibah",
   "format_dokumen_data": "Excel",
   "status": "Terbatas",
   "produsen_data": "Subdit Takol Ditmat Ditjen Kuathan Kemhan",
   "jadwal_pemutakhiran": "Triwulanan, Semesteran, Tahunan",
   "kesepakatan_pengumpulan_data": 0
  },
  {
   "number": 33,
   "no_katalog_data": "683855.2023.020",
   "kode_satker": 683855,
   "tahun": 2023,
   "no_urut": "020",
   "satker": "Ditjen Kuathan Kemhan",
   "nama_dataset": "Rekapitulasi Alutsista dalam Proses Penghapusan",
   "objek_data": "•\tMabes TNI\n•\tTNI AD\n•\tTNI AL\n•\tTNI AU",
   "variabel_pembentuk": "•\tJenis\/Nama Alutsista, Lokasi\n•\tSurat Pengajuan Penghapusan\n•\tTindak Lanjut (Kemhan, Kemenkeu)\n•\tKeterangan",
   "format_dokumen_data": "Excel",
   "status": "Terbatas",
   "produsen_data": "Subdit Takol Ditmat Ditjen Kuathan Kemhan",
   "jadwal_pemutakhiran": "Triwulanan, Semesteran, Tahunan",
   "kesepakatan_pengumpulan_data": 0
  },
  {
   "number": 34,
   "no_katalog_data": "683855.2023.021",
   "kode_satker": 683855,
   "tahun": 2023,
   "no_urut": "021",
   "satker": "Ditjen Kuathan Kemhan",
   "nama_dataset": "Rekapitulasi Data Rumah Negara Kemhan dan TNI",
   "objek_data": "•\tRoum Setjen Kemhan\n•\tMabes TNI\n•\tTNI AD\n•\tTNI AL\n•\tTNI AU",
   "variabel_pembentuk": "•\tUnit Organisasi (U.O.)\n•\tKebutuhan Ideal\n•\tTersedia\n•\tPenghuni (Aktif, Purna\/ Wara, Tidak Berhak)\n•\tKekurangan",
   "format_dokumen_data": "Excel",
   "status": "Terbatas",
   "produsen_data": "Subdit TB Ditfasjas Ditjen Kuathan Kemhan",
   "jadwal_pemutakhiran": "Triwulanan, Semesteran, Tahunan",
   "kesepakatan_pengumpulan_data": 0
  },
  {
   "number": 35,
   "no_katalog_data": "683855.2023.022",
   "kode_satker": 683855,
   "tahun": 2023,
   "no_urut": "022",
   "satker": "Ditjen Kuathan Kemhan",
   "nama_dataset": "Rekapitulasi Data Aset Tanah Kemhan dan TNI",
   "objek_data": "•\tRoum Setjen Kemhan\n•\tMabes TNI\n•\tTNI AD\n•\tTNI AL\n•\tTNI AU",
   "variabel_pembentuk": "•\tUnit Organisasi (U.O.)\n•\tJumlah Tanah\n•\tSertifikat (Sudah, Belum)\n•\tBermasalah",
   "format_dokumen_data": "Excel",
   "status": "Terbatas",
   "produsen_data": "Subdit TB Ditfasjas Ditjen Kuathan Kemhan",
   "jadwal_pemutakhiran": "Triwulanan, Semesteran, Tahunan",
   "kesepakatan_pengumpulan_data": 0
  },
  {
   "number": 36,
   "no_katalog_data": "683855.2023.023",
   "kode_satker": 683855,
   "tahun": 2023,
   "no_urut": "023",
   "satker": "Ditjen Kuathan Kemhan",
   "nama_dataset": "Rekapitulasi Rencana Kebutuhan Bahan Bakar Minyak dan Pelumas Kemhan dan TNI",
   "objek_data": "•\tRoum Setjen Kemhan\n•\tMabes TNI\n•\tTNI AD\n•\tTNI AL\n•\tTNI AU",
   "variabel_pembentuk": "•\tUnit Organisasi (U.O.)\n•\tJenis BMP\n•\tJumlah",
   "format_dokumen_data": "Excel",
   "status": "Terbatas",
   "produsen_data": "Subdit Jasarpras BBMP Ditfasjas Ditjen Kuathan Kemhan",
   "jadwal_pemutakhiran": "Triwulanan, Semesteran, Tahunan",
   "kesepakatan_pengumpulan_data": 0
  },
  {
   "number": 37,
   "no_katalog_data": "683855.2023.024",
   "kode_satker": 683855,
   "tahun": 2023,
   "no_urut": "024",
   "satker": "Ditjen Kuathan Kemhan",
   "nama_dataset": "Rekapitulasi Realisasi Pemakaian Bahan Bakar Minyak dan Pelumas Kemhan dan TNI",
   "objek_data": "•\tRoum Setjen Kemhan\n•\tMabes TNI\n•\tTNI AD\n•\tTNI AL\n•\tTNI AU",
   "variabel_pembentuk": "•\tUnit Organisasi (U.O.)\n•\tJenis BMP\n•\tJumlah",
   "format_dokumen_data": "Excel",
   "status": "Terbatas",
   "produsen_data": "Subdit Jasapras BBMP Ditfasjas Ditjen Kuathan Kemhan",
   "jadwal_pemutakhiran": "Triwulanan, Semesteran, Tahunan",
   "kesepakatan_pengumpulan_data": 0
  },
  {
   "number": 38,
   "no_katalog_data": "683855.2023.025",
   "kode_satker": 683855,
   "tahun": 2023,
   "no_urut": "025",
   "satker": "Ditjen Kuathan Kemhan",
   "nama_dataset": "Rekapitulasi Daftar Rumah Sakit Kemhan dan TNI",
   "objek_data": "•\tPuskes TNI\n•\tDitkesad\n•\tDiskesal\n•\tDiskesau",
   "variabel_pembentuk": "•\tTingkat\n•\tUnit Organisasi (U.O.)\n•\tJumlah",
   "format_dokumen_data": "Excel",
   "status": "Terbatas",
   "produsen_data": "Subdit Kuatkes Ditkes Ditjen Kuathan Kemhan",
   "jadwal_pemutakhiran": "Triwulanan, Semesteran, Tahunan",
   "kesepakatan_pengumpulan_data": 0
  },
  {
   "number": 39,
   "no_katalog_data": "683855.2023.026",
   "kode_satker": 683855,
   "tahun": 2023,
   "no_urut": "026",
   "satker": "Ditjen Kuathan Kemhan",
   "nama_dataset": "Daftar Rumah Sakit Kemhan dan TNI yang Sudah PK BLU",
   "objek_data": "•\tPuskes TNI\n•\tDitkesad\n•\tDiskesal\n•\tDiskesau",
   "variabel_pembentuk": "•\tUnit Organisasi (U.O.)\n•\tNama Rumkit",
   "format_dokumen_data": "Excel",
   "status": "Terbatas",
   "produsen_data": "Subdit Kuatkes Ditkes Ditjen Kuathan Kemhan",
   "jadwal_pemutakhiran": "Triwulanan, Semesteran, Tahunan",
   "kesepakatan_pengumpulan_data": 0
  },
  {
   "number": 40,
   "no_katalog_data": "683855.2023.027",
   "kode_satker": 683855,
   "tahun": 2023,
   "no_urut": "027",
   "satker": "Ditjen Kuathan Kemhan",
   "nama_dataset": "Daftar Rumah Sakit Kemhan dan TNI dalam Proses PK BLU",
   "objek_data": "•\tPuskes TNI\n•\tDitkesad\n•\tDiskesal\n•\tDiskesau",
   "variabel_pembentuk": "•\tUnit Organisasi (U.O.)\n•\tNama Rumkit",
   "format_dokumen_data": "Excel",
   "status": "Terbatas",
   "produsen_data": "Subdit Kuatkes Ditkes Ditjen Kuathan Kemhan",
   "jadwal_pemutakhiran": "Triwulanan, Semesteran, Tahunan",
   "kesepakatan_pengumpulan_data": 0
  },
  {
   "number": 41,
   "no_katalog_data": "683855.2023.028",
   "kode_satker": 683855,
   "tahun": 2023,
   "no_urut": "028",
   "satker": "Ditjen Kuathan Kemhan",
   "nama_dataset": "Daftar Rencana Pengembangan Rumah Sakit Kemhan dan TNI",
   "objek_data": "•\tPuskes TNI\n•\tDitkesad\n•\tDiskesal\n•\tDiskesau",
   "variabel_pembentuk": "•\tUnit Organisasi (U.O.)\n•\tNama Rumkit",
   "format_dokumen_data": "Excel",
   "status": "Terbatas",
   "produsen_data": "Subdit Kuatkes Ditkes Ditjen Kuathan Kemhan",
   "jadwal_pemutakhiran": "Triwulanan, Semesteran, Tahunan",
   "kesepakatan_pengumpulan_data": 0
  },
  {
   "number": 42,
   "no_katalog_data": "683862.2023.001",
   "kode_satker": 683862,
   "tahun": 2023,
   "no_urut": "001",
   "satker": "Baranahan Kemhan",
   "nama_dataset": "Data Personel Pus Alpahan\nBaranahan Kemhan yang sudah memiliki Sertifikat\nPengadaan Barang dan Jasa",
   "objek_data": "Data Personel",
   "variabel_pembentuk": "Nama, Jabatan, Jenis Sertifikat, No.Serfikat",
   "format_dokumen_data": "Excel",
   "status": "Terbatas",
   "produsen_data": "Bidang Matra, Bid Matla, Bid\nMatud, PPBJ Pus Alpahan,\nSubbag TU",
   "jadwal_pemutakhiran": "Real Time",
   "kesepakatan_pengumpulan_data": 0,
   "dasar_hukum": "- Peraturan Menteri Pendayagunaan Aparatur Negara dan Reformasi Birokarsi Nomor 13 Tahun 2019 tentang Pengusulan Penetapan dan Pembinaan Jabatan Fungsional Pegawai Negeri Sipil\n- Keputusan Menteri Pertahanan Nomor: KEP\/1425\/M\/Xl\/2021 tanggal 25 November 2021 tentang Daftar Susunan Personel dan Uraian Tugas Jabatan Fungsional Serta Jabatan Pelaksana Kementerian Pertahanan\n- Surat Kepala Lembaga Kebijakan Pengadaan Barang\/Jasa Pemerintah Nomor:  14139\/D. 3\/1112020 tanggal 03 November 2020 tentang Rekomendasi Kebutuhan Jabatan Fungsional Pengelola Pengadaan Barang\/Jasa (JF PPBJ) di lingkungan Kementerian Pertahanan"
  },
  {
   "number": 43,
   "no_katalog_data": "683862.2023.002",
   "kode_satker": 683862,
   "tahun": 2023,
   "no_urut": "002",
   "satker": "Baranahan Kemhan",
   "nama_dataset": "Data kode pabrik\n(NCAGE NATO)\nCommercial and Government\nEntity",
   "objek_data": "Nama Entitas Pemohon",
   "variabel_pembentuk": "Kode NCAGE, Status, Jenis\nPemohon,  Nama Pemohon,  Alamat, Kota, Kode Pos, Provinsi, Tanggal Publikasi  Data, Tanggal Perubahan",
   "format_dokumen_data": "Excel",
   "status": "Terbatas",
   "produsen_data": "Puskod  Baranahan Kemhan",
   "kesepakatan_pengumpulan_data": 0,
   "dasar_hukum": "Peraturan  Menteri Pertahanan  No.4 Tahun 2014 tentang  Pokok-Pokok Penyelenggaraan Kodifikasi  Materiil Sistem Nomor Sediaan  Nasional\ndi Lingkungan Kemhan dan TNI."
  },
  {
   "number": 44,
   "no_katalog_data": "683862.2023.003",
   "kode_satker": 683862,
   "tahun": 2023,
   "no_urut": "003",
   "satker": "Baranahan Kemhan",
   "nama_dataset": "Data Kode NSN (Nomor Sediaan Nasional)",
   "objek_data": "Data Materiil",
   "variabel_pembentuk": "Kode NIIN, NSC, INC, Nama Baku (Item Name), Tanggal  Penetapan Data, Tanggal\nPerubahan Data, Kode NCAGE, Nomor Referensi\nMateriil, Nama Pabrik ( Manufacture)",
   "format_dokumen_data": "Excel",
   "status": "Terbatas",
   "produsen_data": "Puskod  Baranahan Kemhan",
   "kesepakatan_pengumpulan_data": 0,
   "dasar_hukum": "Peraturan  Menteri Pertahanan  No.4 Tahun 2014 tentang  Pokok-Pokok Penyelenggaraan Kodifikasi  Materiil Sistem Nomor Sediaan  Nasional\ndi Lingkungan Kemhan dan TNI."
  },
  {
   "number": 45,
   "no_katalog_data": "461838.2023.001",
   "kode_satker": 461838,
   "tahun": 2023,
   "no_urut": "001",
   "satker": "Bainstrahan Kemhan",
   "nama_dataset": "Vulnerability Assessment ",
   "objek_data": "Data aset teknologi informasi atau elektronik berbasis web (sistem informasi\/aplikasi\/server) yang bertujuan untuk mengetahui celah keamanan, kerentanan, saran dan rekomendasi  terhadap aset yang dimiliki internal Kemhan (Satuan-satuan Kerja) dan eksternal (K\/L\/D)",
   "variabel_pembentuk": "Formulir pendataan aset teknologi informasi atau elektronik berbasis web (sistem informasi\/aplikasi\/server), yang terdiri dari : \n- Asal Satuan Kerja\n- Nama Aplikasi\/Sistem Informasi\n- Target IP Address\n- Target Domain\/URL\n- Sistem Operasi yang digunakan (Windows, Linux,dll)\n- Web Server yang digunakan (Apache, Nginx, dll)\n- Content Management System (CMS)\/Framework yang digunakan (PHP, CI, dll)\n- E-mail aktif (e-mail asal satker\/instansi yang mengajukan)\n- PIC (Nama Penanggung Jawab asal satker\/instansi)\n- Nomor yang dapat dihubungi (asal satker\/instansi)\n- Upload surat permintaan pengujian celah pada sistem informasi IT\n- Jenis Database yang digunakan (MariaDb, MSSQL,dll)\n- Bahasa Pemrograman yang digunakan (Java, VB, dll)",
   "format_dokumen_data": "PDF",
   "status": "Terbuka",
   "produsen_data": "Pushansiber dan Satker-satker Kemhan",
   "jadwal_pemutakhiran": "Per Semester",
   "link_api": "Akan disiapkan",
   "kesepakatan_pengumpulan_data": 0,
   "dasar_hukum": "a.   Peraturan Menteri Pertahanan Republik Indonesia Nomor  82 Tahun 2014 tentang Pedoman Pertahanan Siber.\nb.   Peraturan Menteri Pertahanan Republik Indonesia Nomor 14 Tahun 2019 tentang Organisasi dan Tata Kerja Kementerian Pertahanan."
  },
  {
   "number": 46,
   "no_katalog_data": "461838.2023.002",
   "kode_satker": 461838,
   "tahun": 2023,
   "no_urut": "002",
   "satker": "Bainstrahan Kemhan",
   "nama_dataset": "Web CSIRT-Kemhan",
   "objek_data": "Rekapitulasi kegiatan CSIRT Pushansiber",
   "variabel_pembentuk": " - User, Password, Article",
   "format_dokumen_data": "Data tidak dapat di ekspor",
   "status": "Terbatas",
   "produsen_data": "Pushansiber",
   "jadwal_pemutakhiran": "Per Semester",
   "kesepakatan_pengumpulan_data": 0,
   "dasar_hukum": "a.   Peraturan Menteri Pertahanan Republik Indonesia Nomor  82 Tahun 2014 tentang Pedoman Pertahanan Siber.\nb.   Peraturan Menteri Pertahanan Republik Indonesia Nomor 14 Tahun 2019 tentang Organisasi dan Tata Kerja Kementerian Pertahanan."
  },
  {
   "number": 47,
   "no_katalog_data": "461838.2023.003",
   "kode_satker": 461838,
   "tahun": 2023,
   "no_urut": "003",
   "satker": "Bainstrahan Kemhan",
   "nama_dataset": "Aplikasi Pusat Kontak dan Tata Kelola",
   "objek_data": "Rekapitulasi Database Aplikasi Pusat Kontak dan Tata Kelola Pushansiber",
   "variabel_pembentuk": " - User, Password, IP Source",
   "format_dokumen_data": ".xls dan .pdf",
   "status": "Terbuka",
   "produsen_data": "Pushansiber",
   "jadwal_pemutakhiran": "Per Semester",
   "kesepakatan_pengumpulan_data": 0,
   "dasar_hukum": "a.   Peraturan Menteri Pertahanan Republik Indonesia Nomor  82 Tahun 2014 tentang Pedoman Pertahanan Siber.\nb.   Peraturan Menteri Pertahanan Republik Indonesia Nomor 14 Tahun 2019 tentang Organisasi dan Tata Kerja Kementerian Pertahanan."
  },
  {
   "number": 48,
   "no_katalog_data": "461838.2023.004",
   "kode_satker": 461838,
   "tahun": 2023,
   "no_urut": "004",
   "satker": "Bainstrahan Kemhan",
   "nama_dataset": "Informasi Strategis Pertahanan ",
   "objek_data": "Rekapitulasi data analisa informasi strategis pertahanan",
   "variabel_pembentuk": "- Atase Pertahanan RI, KBRI, Bais TNI, BIN, Kemlu, Kementerian\/Lembaga Terkait, Open Source, Bidang Dalam Negeri, Bidang Asia Pasifik, Bidang Amerika Eropa dan Afrika",
   "format_dokumen_data": "Excel",
   "status": "Rahasia",
   "produsen_data": "Pusinfostrahan",
   "jadwal_pemutakhiran": "Per Bulan",
   "kesepakatan_pengumpulan_data": 0,
   "dasar_hukum": "a. Permenhan RI Nomor 14 Tahun 2019 tentang Organisasi dan Tata Kerja Kementerian Pertahanan pasal 1198 Pusinfostrahan Bainstrahan Kemhan bertugas melaksanakan kebijakan teknis, serta evaluasi dan pelaporan di bidang pengelolaan informasi strategis pertahanan.\nb. UU No.3 Tahun 2002 tentang Pertahanan Negara\nc.  UU No. 34 Tahun 2004 tentang Tentara Negara Indonesia\nd.  Peraturan Presiden (PERPRES) Nomor 8 Tahun 2021. Kebijakan Umum Pertahanan Negara Tahun 2020-2024"
  },
  {
   "number": 49,
   "no_katalog_data": "461838.2023.005",
   "kode_satker": 461838,
   "tahun": 2023,
   "no_urut": "005",
   "satker": "Bainstrahan Kemhan",
   "nama_dataset": "Pengelolaan Kawasan",
   "objek_data": "Rekapitulasi data analisa Pusat Pengelolaan Kawasan",
   "variabel_pembentuk": "- Pengamanan, Pemeliharaan dan Pembangunan, Serta Pengembangan dan Kerja Sama IPSC Kementerian dan Lembaga meliputi BNPT, BNPB, UNHAN, Pustanda dan Pusbanglin Badan Bahasa Kemendikbud Ristek Serta PMPP Mabes TNI",
   "format_dokumen_data": "Excel",
   "status": "Rahasia",
   "produsen_data": "Puslola ",
   "jadwal_pemutakhiran": "Per Bulan",
   "kesepakatan_pengumpulan_data": 0,
   "dasar_hukum": "a. Permenhan RI Nomor 14 Tahun 2019 tentang Organisasi dan Tata Kerja Kementerian Pertahanan Pasal 1154 Pusat Pengelolaan Kawasan Bainstrahan Kemhan Tugas melaksanakan pengamanan, Pemeliharaan dan Pembangunan, Serta Pengembangan dan Kerja Sama Pengelolaan Instalasi Strategis Pertahanan "
  },
  {
   "number": 50,
   "no_katalog_data": "683009.2023.001",
   "kode_satker": 683009,
   "tahun": 2023,
   "no_urut": "001",
   "satker": "Puslaik Kemhan",
   "nama_dataset": "Sertifikasi Rancang Bangun\/Tipe (Moda Darat, Laut dan Udara)\n",
   "objek_data": "Data Sertifikasi Kelaikan.",
   "variabel_pembentuk": "Nama Barang, Nomor Sertifikat, Pemegang Sertifikat,  Tanggal Penerbitan.",
   "format_dokumen_data": "JSON",
   "status": "Terbuka",
   "produsen_data": "Bidang Kelaikan Darat, Laut & Udara Pusat Kelaikan Kemhan",
   "jadwal_pemutakhiran": "Real Time",
   "link_api": "Akan disiapkan",
   "kesepakatan_pengumpulan_data": 0,
   "dasar_hukum": "Peraturan Menteri Pertahanan No 9 Tahun 2021 tentang Penyelenggaraan Sertifikasi Kelaikan Pertahanan untuk Mendukung Pertahanan Negara"
  },
  {
   "number": 51,
   "no_katalog_data": "686065.2023.001",
   "kode_satker": 686065,
   "tahun": 2023,
   "no_urut": "001",
   "satker": "Pusrehab Kemhan",
   "nama_dataset": "Rekapitulasi Data Penyandang Disabilitas Personel\nKemhan dan TNI",
   "objek_data": "Data Penyandang Disabilitas",
   "variabel_pembentuk": "Kesatuan,\nSudah Rehabilitasi, Belum Rehabilitasi, Tingkat Kecacatan, Jumlah",
   "format_dokumen_data": "Excel",
   "status": "Terbuka",
   "produsen_data": "PUSAT REHABILITASI KEMHAN",
   "jadwal_pemutakhiran": "Pertahun",
   "link_api": "Akan disiapkan",
   "kesepakatan_pengumpulan_data": 0,
   "dasar_hukum": "-UU No.8 tanggal 15 April 2016 tentang Penyandang Disabilitas\n-Peraturan Panglima TNI Nomor 23 Tahun 2013\n-Permenhan Nomor 10 Tahun 2019 tentang penetapan golongan kecacatan dan penetapan status gugur\/tewas bagi pegawai negeri sipil kementerian pertahanan\n-Peraturan Menteri Pertahanan RI Nomor 11 tahun 2021  tetntang pelaksanaan kesamaptaan jasmani bagi prajurit TNI\ndan kesegaran jasmani bagi pegawai PNS Kemhan Pertahun          \n-Juklak\/06\/IX\/2018 tentang pemanggilan calon peserta rehabilitasi terpadu penyandang disabilitas"
  },
  {
   "number": 52,
   "no_katalog_data": "686065.2023.002",
   "kode_satker": 686065,
   "tahun": 2023,
   "no_urut": "002",
   "satker": "Pusrehab Kemhan",
   "nama_dataset": "Rekapitulasi Data Penyandang Disabilitas Personel\nKemhan dan TNI",
   "objek_data": "Data Rehabilitasi Terpadu",
   "variabel_pembentuk": "RTD (Return To Duty)\nWaktu Pelaksanaan :   4,5 Bulan\n\n\nRTC (Return To Combat)\nWaktu Pelaksanaan :          4,5 Bulan",
   "format_dokumen_data": "Excel",
   "status": "Terbuka",
   "produsen_data": "PUSAT REHABILITASI KEMHAN",
   "jadwal_pemutakhiran": "Pertahun",
   "link_api": "Akan disiapkan",
   "kesepakatan_pengumpulan_data": 0
  },
  {
   "number": 53,
   "no_katalog_data": "683841.2023.001",
   "kode_satker": 683841,
   "tahun": 2023,
   "no_urut": "001",
   "satker": "Ditjen Pothan Kemhan",
   "nama_dataset": "Rekapitulasi Data Veteran RI berdasarkan Nomor Pokok Veteran",
   "objek_data": "Data Veteran RI berdasarkan Nomor Pokok Veteran",
   "variabel_pembentuk": "Provinsi, PKRI, Trikora, Dwikora, Seroja, Perdamaian",
   "format_dokumen_data": "Excel",
   "status": "Terbuka",
   "produsen_data": "Dit Veteran Pothan Kemhan",
   "jadwal_pemutakhiran": "Perbulan"
  },
  {
   "number": 54,
   "no_katalog_data": "683841.2023.002",
   "kode_satker": 683841,
   "tahun": 2023,
   "no_urut": "002",
   "satker": "Ditjen Pothan Kemhan",
   "nama_dataset": "Rekapitulasi Data Veteran RI yang masih hidup",
   "objek_data": "Data Veteran RI yang masih hidup",
   "variabel_pembentuk": "Satker, PKRI, Trikora, Dwikora, Seroja, Perdamaian",
   "format_dokumen_data": "Excel",
   "status": "Terbuka",
   "produsen_data": "Dit Veteran Pothan Kemhan",
   "jadwal_pemutakhiran": "Perbulan"
  },
  {
   "number": 55,
   "no_katalog_data": "683841.2023.003",
   "kode_satker": 683841,
   "tahun": 2023,
   "no_urut": "003",
   "satker": "Ditjen Pothan Kemhan",
   "nama_dataset": "Rekapitulasi Komcad",
   "objek_data": "Data Komcad",
   "variabel_pembentuk": "SATUAN\/LEMDIK, JML, KET",
   "format_dokumen_data": "Excel",
   "status": "Terbuka",
   "produsen_data": "Dit Sumdahan Pothan Kemhan",
   "jadwal_pemutakhiran": "bila ada perubahan"
  },
  {
   "number": 56,
   "no_katalog_data": "683841.2023.004",
   "kode_satker": 683841,
   "tahun": 2023,
   "no_urut": "004",
   "satker": "Ditjen Pothan Kemhan",
   "nama_dataset": "Rekap Data Industri Pertahanan",
   "objek_data": "Data Industri Pertahanan",
   "variabel_pembentuk": "Nama Perusahaan, Alamat",
   "format_dokumen_data": "Excel",
   "status": "Terbuka",
   "produsen_data": "Dit Tekindhan Pothan Kemhan",
   "jadwal_pemutakhiran": "bila ada perubahan"
  },
  {
   "number": 57,
   "no_katalog_data": "683841.2023.005",
   "kode_satker": 683841,
   "tahun": 2023,
   "no_urut": "005",
   "satker": "Ditjen Pothan Kemhan",
   "nama_dataset": "Rekap Data Kader Bela Negara",
   "objek_data": "Data Kader Bela Negara",
   "variabel_pembentuk": "Provinsi, Tahun, Jenis",
   "format_dokumen_data": "Excel",
   "status": "Terbuka",
   "produsen_data": "Dit Belneg Pothan Kemhan",
   "jadwal_pemutakhiran": "bila ada perubahan"
  },
  {
   "number": 58,
   "no_katalog_data": "686051.2023.001",
   "kode_satker": 686051,
   "tahun": 2023,
   "no_urut": "001",
   "satker": "Pusdatin Kemhan",
   "nama_dataset": "Rekapitulasi personil pejabat Prakom",
   "objek_data": "Data Prakom Kemhan",
   "variabel_pembentuk": "Satker, Prakom Terampil, Prakom Mahir, Prakom Penyelia, Prakom Ahli Pertama, Prakom Ahli Muda, Prakom Ahli Madya, Prakom Ahli Utama",
   "format_dokumen_data": "Excel",
   "status": "Terbuka",
   "produsen_data": "Pusdatin Kemhan",
   "jadwal_pemutakhiran": "Pertahun"
  },
  {
   "number": 59,
   "no_katalog_data": "686051.2023.002",
   "kode_satker": 686051,
   "tahun": 2023,
   "no_urut": "002",
   "satker": "Pusdatin Kemhan",
   "nama_dataset": "Rekapitulasi Data DPP\/GPP",
   "objek_data": "Data DPP\/GPP",
   "variabel_pembentuk": "Pangkat, UO, Jumlah, Bulan, Tahun, Status\/Jenis Personel",
   "format_dokumen_data": "Excel",
   "status": "Tertutup",
   "produsen_data": "Pusdatin Kemhan",
   "jadwal_pemutakhiran": "Perbulan"
  },
  {
   "number": 60,
   "no_katalog_data": "683820.2023.001",
   "kode_satker": 683820,
   "tahun": 2023,
   "no_urut": "001",
   "satker": "Ditjen Strahan Kemhan",
   "nama_dataset": "Peta Wilayah Pertahanan Negara skala 1:1.000.000",
   "objek_data": "Seluruh wilayah Indonesia",
   "variabel_pembentuk": "Nomor, Nama Wilayah Pertahanan, Lokasi Wilayah Pertahanan, Index, Lintang, Bujur, Keterangan, Jenis Wilayah Pertahanan, Koed Unsur, Kode Layar",
   "format_dokumen_data": "Shapefile \/ Geodatabase",
   "jenis_data": "Geospasial",
   "status": "Terbatas",
   "produsen_data": "Dit Wilhan Ditjen Strahan Kemhan",
   "link_api": "Akan disiapkan",
   "kesepakatan_pengumpulan_data": 0,
   "dasar_hukum": "Perpres Nomor 23 Tahun 2021 tentang erubahan Atas Peraturan Presiden Nomor 9 Tahun 2016 Tentang Percepatan Pelaksanaan Kebijakan Satu Peta Pada Tingkat Ketelitian Peta Skala 1:50.000"
  },
  {
   "number": 61,
   "no_katalog_data": "683820.2023.002",
   "kode_satker": 683820,
   "tahun": 2023,
   "no_urut": "002",
   "satker": "Ditjen Strahan Kemhan",
   "nama_dataset": "Peta Rinci Wilayah Pertahanan Negara skala 1:50.000",
   "objek_data": "Seluruh wilayah Indonesia",
   "variabel_pembentuk": "Nomor, Nama Wilayah Pertahanan, Lokasi Wilayah Pertahanan, Index, Lintang, Bujur, Keterangan, Jenis Wilayah Pertahanan, Koed Unsur, Kode Layar",
   "format_dokumen_data": "Shapefile \/ Geodatabase",
   "jenis_data": "Geospasial",
   "status": "Terbatas",
   "produsen_data": "Dit Wilhan Ditjen Strahan Kemhan",
   "link_api": "Akan disiapkan",
   "kesepakatan_pengumpulan_data": 0,
   "dasar_hukum": "Perpres Nomor 23 Tahun 2021 tentang erubahan Atas Peraturan Presiden Nomor 9 Tahun 2016 Tentang Percepatan Pelaksanaan Kebijakan Satu Peta Pada Tingkat Ketelitian Peta Skala 1:50.000"
  }
 ]